const chatConstants = {
  MESSAGE_SAVE_REQUEST: 'MESSAGE_SAVE_REQUEST',
  MESSAGE_SAVE_SUCCESS: 'MESSAGE_SAVE_SUCCESS',
  MESSAGE_SAVE_FAILURE: 'MESSAGE_SAVE_FAILURE',
  GET_MESSAGE_REQUEST: 'GET_MESSAGE_REQUEST',
  GET_MESSAGE_SUCCESS: 'GET_MESSAGE_SUCCESS',
  GET_MESSAGE_FAILURE: 'GET_MESSAGE_FAILURE',
};

export default chatConstants;
