const jobConstants = {
  ADD_JOB_REQUEST: 'ADD_JOB_REQUEST',
  ADD_JOB_SUCCESS: 'ADD_JOB_SUCCESS',
  ADD_JOB_FAILURE: 'ADD_JOB_FAILURE',
  EDIT_JOB_REQUEST: 'EDIT_JOB_REQUEST',
  EDIT_JOB_SUCCESS: 'EDIT_JOB_SUCCESS',
  EDIT_JOB_FAILURE: 'EDIT_JOB_FAILURE',
  UPDATE_JOB_REQUEST: 'UPDATE_JOB_REQUEST',
  UPDATE_JOB_SUCCESS: 'UPDATE_JOB_SUCCESS',
  UPDATE_JOB_FAILURE: 'UPDATE_JOB_FAILURE',
  APPLY_JOB_REQUEST: 'APPLY_JOB_REQUEST',
  APPLY_JOB_SUCCESS: 'APPLY_JOB_SUCCESS',
  APPLY_JOB_FAILURE: 'APPLY_JOB_FAILURE',
  GET_APPLIED_JOB_REQUEST: 'GET_APPLIED_JOB_REQUEST',
  GET_APPLIED_JOB_SUCCESS: 'GET_APPLIED_JOB_SUCCESS',
  GET_APPLIED_JOB_FAILURE: 'GET_APPLIED_JOB_FAILURE',
  REMOVE_JOB_REQUEST: 'REMOVE_JOB_REQUEST',
  REMOVE_JOB_SUCCESS: 'REMOVE_JOB_SUCCESS',
  REMOVE_JOB_FAILURE: 'REMOVE_JOB_FAILURE',
  UPDATE_APPLIED_STATUS_REQUEST: 'UPDATE_APPLIED_STATUS_REQUEST',
  UPDATE_APPLIED_STATUS_SUCCESS: 'UPDATE_APPLIED_STATUS_SUCCESS',
  UPDATE_APPLIED_STATUS_FAILURE: 'UPDATE_APPLIED_STATUS_FAILURE'
};

export default jobConstants;
