const fetchJobByCompanyConstant = {
  FETCH_JOB_BY_COMPANY_REQUEST: 'FETCH_JOB_BY_COMPANY_REQUEST',
  FETCH_JOB_BY_COMPANY_SUCCESS: 'FETCH_JOB_BY_COMPANY_SUCCESS',
  FETCH_JOB_BY_COMPANY_FAILURE: 'FETCH_JOB_BY_COMPANY_FAILURE'
}

export default fetchJobByCompanyConstant;