const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  USERS_LOGOUT_REQUEST: 'USERS_LOGOUT_REQUEST',
  USERS_LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',
  USERS_LOGOUT_FAILURE: 'USERS_LOGOUT_FAILURE',

  GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',

  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  BAN_USER_REQUEST: 'BAN_USER_REQUEST',
  BAN_USER_SUCCESS: 'BAN_USER_SUCCESS',
  BAN_USER_FAILURE: 'BAN_USER_FAILURE',

  PROMOTE_USER_REQUEST: 'PROMOTE_USER_REQUEST',
  PROMOTE_USER_SUCCESS: 'PROMOTE_USER_SUCCESS',
  PROMOTE_USER_FAILURE: 'PROMOTE_USER_FAILURE',
};

export default userConstants;
